// AUTO GENERATED by solunaapi_impl.temp.c, DONT EDIT

#include <stddef.h>

#include "sokol/sokol_gfx.h"

#define SOLUNA_EXT_API_VERSION 2

struct soluna_vec2 {
	float x;
	float y;
};

struct soluna_basis {
	struct soluna_vec2 origin;
	struct soluna_vec2 axis_x;
	struct soluna_vec2 axis_y;
};

struct soluna_sprite_rect {
	int texture;
	float u;
	float v;
	float w;
	float h;
	float ox;
	float oy;
};

struct soluna_material_stream_item {
	float x;
	float y;
	int sprite;
	const void *payload;
};

struct soluna_material_stream_data {
	float x;
	float y;
	int sprite;
};

struct soluna_material_stream_basis {
	struct soluna_basis basis;
	int sprite;
};

struct soluna_material_stream {
	char *data;
	size_t size;
};

typedef const char *soluna_material_error;

struct soluna_material_stream_context {
	void *ctx;
};

struct soluna_render_bindings {
	void *ctx;
};

struct soluna_sprite_bank {
	void *ctx;
};

struct soluna_font_manager {
	void *ctx;
};

struct soluna_font_glyph {
	int offset_x;
	int offset_y;
	int advance_x;
	int advance_y;
	int width;
	int height;
	int atlas_x;
	int atlas_y;
};

struct soluna_font_metrics {
	int ascent;
	int descent;
	int line_gap;
};

struct soluna_font_atlas {
	int width;
	int height;
	int glyph_width;
	int glyph_height;
	float sdf_mask;
	float sdf_distance;
};

typedef void (*soluna_material_submit_func)(void *ud, struct soluna_material_stream_context ctx, int n);
typedef void (*soluna_material_stream_write_func)(void *ud, int index, struct soluna_material_stream_item *item);


extern soluna_material_error material_submit(const void *stream, int prim_n, int material_id, int batch_n, void *ud, soluna_material_submit_func submit);
extern int material_sprite_rect(struct soluna_sprite_bank bank, int sprite, struct soluna_sprite_rect *out);
extern sg_bindings material_bindings(struct soluna_render_bindings bindings);
extern soluna_material_error material_push_stream(int material_id, int count, size_t payload_size, soluna_material_stream_write_func write, void *ud, struct soluna_material_stream *out);
extern void material_stream_free(void *ptr);
extern int material_stream_read(struct soluna_material_stream_context ctx, int index, size_t payload_size, void *payload, struct soluna_material_stream_data *out);
extern int material_stream_read_basis(struct soluna_material_stream_context ctx, int index, size_t payload_size, void *payload, struct soluna_material_stream_basis *out);
extern void material_stream_error(struct soluna_material_stream_context ctx, const char *error);
extern int material_stream_failed(struct soluna_material_stream_context ctx);
extern const char * font_measure(struct soluna_font_manager font, int font_id, int codepoint, int size, struct soluna_font_glyph *glyph);
extern const char * font_atlas_glyph(struct soluna_font_manager font, int font_id, int codepoint, int size, struct soluna_font_glyph *glyph, struct soluna_font_glyph *atlas);
extern int font_metrics(struct soluna_font_manager font, int font_id, int size, struct soluna_font_metrics *out);
extern int font_atlas(struct soluna_font_manager font, struct soluna_font_atlas *out);

struct soluna_api {
	int version;

	soluna_material_error (*material_submit) (const void *stream, int prim_n, int material_id, int batch_n, void *ud, soluna_material_submit_func submit);
	int (*material_sprite_rect) (struct soluna_sprite_bank bank, int sprite, struct soluna_sprite_rect *out);
	sg_bindings (*material_bindings) (struct soluna_render_bindings bindings);
	soluna_material_error (*material_push_stream) (int material_id, int count, size_t payload_size, soluna_material_stream_write_func write, void *ud, struct soluna_material_stream *out);
	void (*material_stream_free) (void *ptr);
	int (*material_stream_read) (struct soluna_material_stream_context ctx, int index, size_t payload_size, void *payload, struct soluna_material_stream_data *out);
	int (*material_stream_read_basis) (struct soluna_material_stream_context ctx, int index, size_t payload_size, void *payload, struct soluna_material_stream_basis *out);
	void (*material_stream_error) (struct soluna_material_stream_context ctx, const char *error);
	int (*material_stream_failed) (struct soluna_material_stream_context ctx);
	const char * (*font_measure) (struct soluna_font_manager font, int font_id, int codepoint, int size, struct soluna_font_glyph *glyph);
	const char * (*font_atlas_glyph) (struct soluna_font_manager font, int font_id, int codepoint, int size, struct soluna_font_glyph *glyph, struct soluna_font_glyph *atlas);
	int (*font_metrics) (struct soluna_font_manager font, int font_id, int size, struct soluna_font_metrics *out);
	int (*font_atlas) (struct soluna_font_manager font, struct soluna_font_atlas *out);
};

struct soluna_api *
extlua_soluna_api() {
	static struct soluna_api api = {
		SOLUNA_EXT_API_VERSION,

		material_submit,
		material_sprite_rect,
		material_bindings,
		material_push_stream,
		material_stream_free,
		material_stream_read,
		material_stream_read_basis,
		material_stream_error,
		material_stream_failed,
		font_measure,
		font_atlas_glyph,
		font_metrics,
		font_atlas,
	};
	return &api;
}
