// AUTO GENERATED by ../src/extapi_types.temp.h, DONT EDIT

#ifndef SOLUNA_EXTAPI_TYPES_H
#define SOLUNA_EXTAPI_TYPES_H

#include <stddef.h>

#include "sokol/sokol_gfx.h"

#define SOLUNA_EXT_API_VERSION 2

struct soluna_vec2 {
	float x;
	float y;
};

struct soluna_basis {
	struct soluna_vec2 origin;
	struct soluna_vec2 axis_x;
	struct soluna_vec2 axis_y;
};

struct soluna_sprite_rect {
	int texture;
	float u;
	float v;
	float w;
	float h;
	float ox;
	float oy;
};

struct soluna_material_stream_item {
	float x;
	float y;
	int sprite;
	const void *payload;
};

struct soluna_material_stream_data {
	float x;
	float y;
	int sprite;
};

struct soluna_material_stream_basis {
	struct soluna_basis basis;
	int sprite;
};

struct soluna_material_stream {
	char *data;
	size_t size;
};

typedef const char *soluna_material_error;

struct soluna_material_stream_context {
	void *ctx;
};

struct soluna_render_bindings {
	void *ctx;
};

struct soluna_sprite_bank {
	void *ctx;
};

struct soluna_font_manager {
	void *ctx;
};

struct soluna_font_glyph {
	int offset_x;
	int offset_y;
	int advance_x;
	int advance_y;
	int width;
	int height;
	int atlas_x;
	int atlas_y;
};

struct soluna_font_metrics {
	int ascent;
	int descent;
	int line_gap;
};

struct soluna_font_atlas {
	int width;
	int height;
	int glyph_width;
	int glyph_height;
	float sdf_mask;
	float sdf_distance;
};

typedef void (*soluna_material_submit_func)(void *ud, struct soluna_material_stream_context ctx, int n);
typedef void (*soluna_material_stream_write_func)(void *ud, int index, struct soluna_material_stream_item *item);


#endif
